name: Frontend React Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v3

      - name: 🔧 Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install Dependencies
        run: |
          cd zealthy-frontend
          npm install

      - name: 🚧 Build Frontend
        run: |
          cd zealthy-frontend
          npm run build
